on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer
      - name: Installation des dépendances
        run: composer install --no-progress --no-suggest --no-interaction
      - name: Lancement des tests PHPUnit
        run: vendor/bin/phpunit --testdox

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Installation des dépendances
        run: composer install --no-progress --no-suggest --no-interaction
      - name: Analyse PHPStan
        run: vendor/bin/phpstan analyse --no-progress

  phpcsfixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Installation des dépendances
        run: composer install --no-progress --no-suggest --no-interaction
      - name: Vérification du style de code
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

  deploy:
    name: Déploiement sur lesacteursduweb.fr
    runs-on: ubuntu-latest
    needs: [phpunit, phpstan, phpcsfixer]
    if: ${{ success() }}
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Configuration SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Déploiement sur le serveur distant
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@lesacteursduweb.fr "
            cd ~/www_github &&
            git pull origin main &&
            composer install --no-dev --no-interaction --prefer-dist
          "